name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit 🛎️
        uses: actions/checkout@v6.0.2

      - name: Install Node ⬢
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16.x'
      
      - name: Install 🔧
        run: |
          npm install --legacy-peer-deps

      - name: Build 🧩
        run: |
          npm run build

      - name: Test 🧪
        run: |
          set -e
          npm test

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: build
